[versions]
agp = "8.13.2"
android-compileSdk = "36"
android-minSdk = "29"
android-targetSdk = "36"
androidx-activityCompose = "1.12.2"
compose-plugin = "1.9.3"
kotlin = "2.3.0"
korender = "0.6.1"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
korender = { module = "com.github.zakgof:korender", version.ref = "korender" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }